name: k6 Load Test

on:
  push:
    branches:
      - '**'

jobs:
  run-k6-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup K6
        uses: grafana/setup-k6-action@v1
      - name: Run local k6 test
        uses: grafana/run-k6-action@v1
        with:
          path: x/test.js

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: k6-action-report
          path: apiTestSummaryReport.html